---
title: "Países colonizados são mais pobres?"
author: "Guilherme Ventura"
date: "18/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Bibliotecas
```{r echo=FALSE}
install.packages("pacman")
library(pacman)

p_load(readxl, tidyverse)
```


Dados de colonização tirados do CEPII
```{r}
colonizados <- read_excel("dados/geo_cepii.xls")
pobreza <-  read.csv("dados/Multidimensional poverty index (MPI).csv")
idh <- read.csv("dados/Human Development Index (HDI).csv")
```

Tratando dados
Primeiramente os dados do CEPII
```{r}
colonizados <- 
  colonizados %>% 
    select(iso3, country, continent, colonizer1, colonizer2, colonizer3, colonizer4, short_colonizer1) %>% 
    rename(sigla = iso3, pais = country, continente = continent, colonizador_1 = colonizer1, colonizador_2 = colonizer2,
           colonizador_3 = colonizer3, colonizador_4 = colonizer4, colonizacao_rapida = short_colonizer1)
  
colonizados$colonizador_1 = str_replace(colonizados$colonizador_1, ".", "") 
colonizados$colonizador_2 = str_replace(colonizados$colonizador_2, ".", "") 
colonizados$colonizador_3 = str_replace(colonizados$colonizador_3, ".", "") 
colonizados$colonizador_4 = str_replace(colonizados$colonizador_4, ".", "")
colonizados$colonizador_4 = str_replace(colonizados$colonizador_4, ".", "")
colonizados$colonizacao_rapida = str_replace(colonizados$colonizacao_rapida, ".", "")





```

